version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=udb
    # Exclude port forwarding to the host for MySQL
    networks:
      - app-network
    restart: always

  redis:
    image: redis:latest
    container_name: redis-container
    # Exclude port forwarding to the host for Redis
    networks:
      - app-network
    restart: always

  go-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-container
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

